### ISSUE TITLE
Use gulp-umd to keep the src folder clean

### ISSUE THREAD

**Issue by chrisdwheatley** [chrisdwheatley/material-design-hamburger#9]
Clean the js in the `src` folder to ensure that linting doesn't throw errors. Possibly using https://github.com/eduardolundgren/gulp-umd although haven't looked into it enough yet.

**Comment by chrisdwheatley** [comment]
Any thoughts on this @zakangelle? I gave gulp-umd a go but it didn't give the same output as the UMD work you provided. Where did you get your UMD code from?

**Comment by zxqx** [comment]
Yes, definitely agree with giving this a go. I wouldn't worry too much if it doesn't give you the same output, as long as it works.

**Comment by chrisdwheatley** [comment]
This is now working in 0.2.1
